sudo: required
services:
  - docker

before_install:
  - docker build -t apescape/react_docker -f Dockerfile.dev .

script:
  - docker run -e CI=true apescape/react_docker npm run test

deploy:
  provider: heroku
  api_key:
    secure: "8a0c57b9-f59d-4283-bfa8-316eff88eb91"
  app: react-docker
  on:
    branch: master
