sudo: required
services:
  - docker

before_install:
  - docker login -u=_ -p=$HEROKU_API_KEY registry.heroku.com

script:
  - docker build -t $DOCKER_TAG -f Dockerfile.dev .
  - docker run -e CI=true $DOCKER_TAG npm run test
  - docker tag $DOCKER_TAG registry.heroku.com/$HEROKU_APP_NAME/web

deploy:
  provider: script
  skip_cleanup: true
  script:
    docker build -t $DOCKER_TAG -f Dockerfile.dev .
    
    docker push registry.heroku.com/$HEROKU_APP_NAME/web
  on:
    branch: master
