sudo: required
services:
  - docker

before_install:
  # install heroku CLI
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - docker login -u=_ -p=$HEROKU_API_KEY registry.heroku.com

script:
  - docker build -t $DOCKER_TAG -f Dockerfile.dev .
  - docker run -e CI=true $DOCKER_TAG npm run test

deploy:
  provider: script
  script:
    #Push a Heroku container
    #docker build -t $DOCKER_TAG -f Dockerfile.dev .
    #docker tag $DOCKER_TAG $HEROKU_APP_NAME/web
    #docker push registry.heroku.com/$HEROKU_APP_NAME/web
    heroku container:push web --app $HEROKU_APP_NAME
    heroku container:release web --app $HEROKU_APP_NAME
  on:
    branch: master
